Implement the Py API
cpppracticum/cpp-backend-tests-practicum pull request #16
Opened 2022-12-02 04:13 UTC by AwesomeAlexey

2022-12-06 09:42 UTC, wo1f requested changes

2022-12-06 09:42 UTC, wo1f commented on tests/cpp_server_api.py
> +    @property
использовать property ради геттера, который просто возвращает, не pythonic-way

2022-12-06 09:42 UTC, wo1f commented on tests/cpp_server_api.py
> +            raise WrongFields('Join game response', ['authToken', 'playerId'], list(res_json.keys()))
Содержать что-то еще -- не преступление)

2022-12-06 09:42 UTC, wo1f commented on tests/cpp_server_api.py
> +        except AttributeError:
Откуда это может взяться?

2022-12-06 09:42 UTC, wo1f commented on tests/cpp_server_api.py
> +class WrongFields(UnexpectedData):
Чет не понял различия между WrongFields и UnexpectedData

2022-12-07 16:50 UTC, AwesomeAlexey commented on tests/cpp_server_api.py
> +        except AttributeError:
Если попросили state игрока под айди, которого нет на карте, к которой привязан токен (токен и айди ведь живут раздельно, state игрока надо самостоятельно вытаскивать, если я не пропустил ничего)

2022-12-12 16:40 UTC, merged