Feature docker api
cpppracticum/cpp-backend-tests-practicum pull request #31
Opened 2023-01-23 19:57 UTC by AwesomeAlexey

2023-01-23 20:58 UTC, wo1f requested changes

2023-01-23 20:58 UTC, wo1f commented on tests/cpp_server_api.py
> +    def __init__(self, server_domain: str, port: [str, int] = '8080', image: str = None, **extra_kwargs):
мм, а что это за hint на port?
почему hint на image не Optional?

2023-01-23 20:58 UTC, wo1f commented on tests/test_s02_time_control.py
> +    docker_server = docker_server
что тут произошло?

2023-01-26 11:59 UTC, wo1f commented on tests/cpp_server_api.py
> +import typing
зачем?

2023-01-26 11:59 UTC, wo1f commented on tests/cpp_server_api.py
> +        except KeyboardInterrupt:
зачем?

2023-01-26 11:59 UTC, wo1f commented on tests/cpp_server_api.py
> +                    raise Exception({'message': 'Cannot get the right start phrase from the container.',
просто Exception?

2023-01-26 11:59 UTC, wo1f commented on tests/cpp_server_api.py
> +                raise Exception('Container does not exist')
просто Exception?

2023-01-26 11:59 UTC, wo1f commented on tests/cpp_server_api.py
> +            name = inspector.inspect_container(self.container.id)['Name'][1:]
кинь тут коммент зачем такой хак

2023-01-26 11:59 UTC, wo1f commented on tests/cpp_server_api.py
> +                time.sleep(1)
иногда, правильной стратегией является увеличивать время в 2 раза, но тут не уверен

2023-01-26 11:59 UTC, wo1f commented on tests/test_s02_time_control.py
> +    return game.GameServer(config_path)
а в чем смысл замены?

2023-01-26 11:59 UTC, wo1f commented on tests/test_s02_time_control.py
> +    random.seed(345612)
укажи что это хак, и когда ты его уберешь)

2023-01-26 11:59 UTC, wo1f commented on tests/test_s02_time_control.py
> +    random.seed(65487473)
тоже самое

2023-01-26 11:59 UTC, wo1f commented on tests/test_s04_leave_game.py
> +        return 15.0    # Default value
magic number

2023-01-26 13:58 UTC, AwesomeAlexey commented on tests/cpp_server_api.py
> +import typing
os - вытаскивать переменную окружения при поднятии докера,
re - вытаскивать "Server has started" из контейнера по паттерну
time - делать задержку для ожидания логов
typing убрал, он правда оказался лишним

2023-01-26 14:00 UTC, AwesomeAlexey commented on tests/test_s02_time_control.py
> +    return game.GameServer(config_path)
В yield нет нужны, return как-то очевиднее, что ли

2023-01-26 16:36 UTC, wo1f commented on tests/cpp_server_api.py
> +import typing
да, я про него и говорил, github просто отображает строчку + 3 сверху)

2023-01-26 16:52 UTC, AwesomeAlexey commented on tests/cpp_server_api.py
> +                time.sleep(1)
Как правило, он даже внутрь цикла не заходит, поэтому тут заморачиваться с какими-то алгоритмами изменения шага ожидания нет смысла, мне кажется. Если там так и не будет нужного сообщения - всё равно через три секунды выйдет. А если будет - после первого захода почти наверняка должен найти его в логах

2023-01-27 09:15 UTC, wo1f requested changes
почти)

2023-01-27 09:15 UTC, wo1f commented on tests/cpp_server_api.py
> +            pattern = '[Ss]erver (has )?started'
Ну камон, я же говорил что расползлось

2023-01-27 09:15 UTC, wo1f commented on tests/cpp_server_api.py
> +            print(res.status_code, res.content)
print?

2023-01-27 09:15 UTC, wo1f commented on tests/test_s04_leave_game.py
> +DEFAULT_RETIREMENT_TIME = 60.0  # Значение по умолчанию из задания
коммент избыточный, но в целом придираюсь

2023-01-27 09:15 UTC, wo1f commented on tests/test_s04_leave_game.py
> +    except TypeError:
если поведение в ветках except одинаковое, можно объединить запятой

2023-01-27 09:22 UTC, wo1f commented on tests/test_s04_leave_game.py
> +    except TypeError:
а откуда может взяться TypeError?

2023-01-27 10:57 UTC, AwesomeAlexey commented on tests/test_s04_leave_game.py
> +    except TypeError:
TypeError - мог возникнуть, когда get_config не смог бы достать конфиг и вернул бы None. Но теперь правда не может - get_config выкинет исключение, если не сможет распарсить конфиг - убрал

2023-01-27 11:19 UTC, wo1f approved these changes

2023-01-27 14:49 UTC, merged